module 1 task 2
js-tasks-ru/jsbasic-20230428_yuliapobereznichenko pull request #3
Opened 2023-05-06 16:29 UTC by YPobereznichenko

2023-05-06 16:30 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-06 17:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-06 18:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-07 11:27 UTC, SinimaWath requested changes

2023-05-07 11:27 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return true;
Давай попробуем записать это условие в одну строчку, с && или || операторами

2023-05-07 11:27 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
`return str.includes('1xbet') || str.includes('xxx')` - так как результат операции boolean, if не нужен

2023-05-10 23:16 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-12 07:24 UTC, SinimaWath approved these changes

2023-05-12 07:24 UTC, merged